BEGIN TRANSACTION	UPDATECONTATO
MERGE INTO AC8010 T
   USING SU5010 S 
      ON T.AC8_CODCON = S.U5_CODCONT	         
WHEN MATCHED THEN
   UPDATE 
      SET T.AC8_XNOME = S.U5_CONTAT , 
      T.AC8_XEMAIL = S.U5_EMAIL;	
          
COMMIT
		  SELECT AC8_XNOME,U5_CONTAT,AC8_XEMAIL,U5_EMAIL,U5_CODCONT,AC8_CODCON FROM AC8010 AC8 INNER JOIN SU5010 SA1 ON AC8_CODCON = SA1.U5_CODCONT	