-------------------CTE COM CURSOR percorrendo a CTE----------------

DECLARE @CODIGO VARCHAR(6)
DECLARE @NOME VARCHAR(50)
DECLARE cursorSA1 CURSOR FOR

WITH CLIENTES (CODIGO,NOME)
AS (SELECT A1_COD, A1_NOME FROM SA1010 WHERE D_E_L_E_T_ = '')

SELECT * FROM CLIENTES
OPEN cursorSA1 
FETCH NEXT FROM cursorSA1 INTO @CODIGO, @NOME

WHILE @@FETCH_STATUS = 0
	BEGIN
		PRINT @CODIGO + @NOME
		FETCH NEXT FROM cursorSA1 INTO @CODIGO, @NOME
	END
CLOSE curosrSA1
DEALLOCATE cursorSA1