BEGIN TRANSACTION	UPDATENOMECLIENTE
MERGE INTO SCJ010 T
   USING SA1010 S 
      ON T.CJ_CLIENTE = S.A1_COD	         
WHEN MATCHED THEN
   UPDATE 
      SET T.CJ_XNREDUZ = S.A1_NREDUZ; 
          
COMMIT
		  SELECT CJ_XNREDUZ,A1_NREDUZ FROM SCJ010 SCJ INNER JOIN SA1010 SA1 ON SCJ.CJ_CLIENTE = SA1.A1_COD
		  SELECT * FROM SCJ010
		  select * from SA1010