BEGIN TRANSACTION	UPDATENOMECLIENTE
MERGE INTO SC5010 T
   USING SA1010 S 
      ON T.C5_CLIENTE = S.A1_COD	         
WHEN MATCHED AND C5_TIPO = 'N' THEN
   UPDATE 
      SET T.C5_XNOME = S.A1_NREDUZ; 


MERGE INTO SC5010 T
   USING (SELECT A2_COD, A2_NREDUZ FROM SA2010 WHERE D_E_L_E_T_ = '') AS S
      ON T.C5_CLIENTE = S.A2_COD	         
WHEN MATCHED AND C5_TIPO = 'B' OR C5_TIPO = 'D' THEN
   UPDATE 
      SET T.C5_XNOME = S.A2_NREDUZ; 

COMMIT
		  
		  
----------------------SELECT DE VERIFICAÇÃO------------------------------------------------------		  
		--  SELECT C5_NUM,C5_XNOME, C5_CLIENTE,C5_TIPO FROM SC5010 WHERE C5_TIPO = 'D'
		--  SELECT C5_XNOME,A1_NREDUZ FROM SCJ010 SCJ INNER JOIN SA1010 SA1 ON SCJ.CJ_CLIENTE = SA1.A1_COD
		--  SELECT * FROM SCJ010
		--  select * from SA2010
--------------