SELECT A1_COD FROM SA1010 WHERE D_E_L_E_T_ = '' UNION ALL SELECT A2_COD FROM SA2010  WHERE D_E_L_E_T_ = ''

SELECT A1_COD FROM SA1010 WHERE D_E_L_E_T_ = '' EXCEPT SELECT A2_COD FROM SA2010  WHERE D_E_L_E_T_ = ''

SELECT A1_COD FROM SA1010 WHERE D_E_L_E_T_ = '' INTERSECT SELECT A2_COD FROM SA2010  WHERE D_E_L_E_T_ = ''